### ISSUE TITLE
Why is subtraction used in _XACTUAL calculation

### ISSUE THREAD

**Issue by orangeccc** [MichaelHotaling/klarfkit#1]
hi,
Good work!
I got a question about your code.
Why is subtraction used in _XACTUAL at
https://github.com/MichaelHotaling/klarfkit/blob/8364577fa83f33adb857f982fb6252422f8c2db5/klarfkit/klarfkit.py#L58-L59
I think maybe it should be 
`df['_XACTUAL'] = (df['XINDEX'] * self.die_pitch[0]) + df['XREL'] + self.center_location[0]`
`df['_YACTUAL'] = (df['YINDEX'] * self.die_pitch[1]) + df['YREL'] + self.center_location[1]`?

**Comment by orangeccc** [comment]
oh, I think i got it.
is the center location means the wafer center coordinate with 0, 0 die as origin?

and i found that the die lines in the output result map is different with another [software's.].
(https://slriley.com/software/klarfview-overview-2/)
![1a](https://user-images.githubusercontent.com/31794133/182114320-a4616db7-0c0d-4639-b384-2317b7a8db9d.png)


![1b](https://user-images.githubusercontent.com/31794133/182114367-f590bf2e-f448-44b2-ae0e-d7d1b32adb82.png)
(Note the points and lines on the left.)


after i edit the line
https://github.com/MichaelHotaling/klarfkit/blob/8364577fa83f33adb857f982fb6252422f8c2db5/klarfkit/klarfkit.py#L77
and
https://github.com/MichaelHotaling/klarfkit/blob/8364577fa83f33adb857f982fb6252422f8c2db5/klarfkit/klarfkit.py#L91
to
`die_x_lines = -self.center_location[0] + (i * self.die_pitch[0])`
`die_y_lines = -self.center_location[1] + (i * self.die_pitch[1])`,
then they are exactly the same.

![2](https://user-images.githubusercontent.com/31794133/182114607-d48d3391-dbd0-4892-b177-04231e13812a.png)
![1b](https://user-images.githubusercontent.com/31794133/182114367-f590bf2e-f448-44b2-ae0e-d7d1b32adb82.png)

so maybe there shoud be a minus in die lines calculation?

**Comment by MichaelHotaling** [comment]
Nice find!
I've added the changes into the code base.

https://github.com/MichaelHotaling/klarfkit/commit/df8727428d1f0c9d2a27c101b194b562d2c4d72b
