### ISSUE TITLE
about klarf corordinates

### ISSUE THREAD

**Issue by Tibalt** [MichaelHotaling/klarfkit#3]
I am confused about three coordinates: sample coordinates, alignment image coordinates, and database coordinates.

Can you help me to understand?

**Comment by MichaelHotaling** [comment]
KLARF files contain a few coordinate values.

DiePitch shows the size of the die
SampleCenterLocation  is the central die which shows the position relative to other dies

The defects have both relative die position and position inside the die. 

| DEFECTID | XREL | YREL | XINDEX | YINDEX | XSIZE | YSIZE | DEFECTAREA | DSIZE | CLASSNUMBER | TEST | ROUGHBINNUMBER | IMAGECOUNT | IMAGELIST |
| -------- | ---- | ---- | ------- | ------- | ------ | ------ | ---------- | ----- | ----------- | ---- | -------------- | ---------- | --------- | 
| 1        | 5.5264000000e+02 | 1.0430800000e+03 | -35 | -9 | 2.680000 | 3.640000 | 9.755200 | 4.5206407965e+00 | 0

XREL and YREL shows the position inside the die where the defect is.
XINDEX and YINDEX says which die.

**Comment by MichaelHotaling** [comment]
No actions needed.
